# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package and tsconfig files
COPY package.json tsconfig.json ./

# Copy source files
COPY src/ ./src/

# Install dependencies (ignore optional install scripts to speed up build)
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

# Expose port if needed (not necessary if using stdio for MCP)

# Set command to run the server
CMD [ "node", "dist/index.js" ]
